name: qsu
description: >-
  QSU is a lightweight and simple module with a variety of built-in utility functions that you can utilize in your Dart projects.
version: 0.0.1
repository: https://github.com/jooy2/qsu-dart
homepage: https://cdget.com

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
