name: qsu
description: >-
  QSU is a lightweight and simple module with a variety of built-in utility functions that you can utilize in your Dart projects.
version: 0.0.3
repository: https://github.com/jooy2/qsu-dart
homepage: https://qsu.cdget.com

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: 4.0.0
  test: 1.25.7
